x = train_data_reshaped(train_i, :);
xg = gpuArray(x);
tic
feature_vec = [
        EEG_feature_extractor.extract_relative_power(x, Fs, [0.5, 4]), ...  
        EEG_feature_extractor.extract_relative_power(x, Fs, [4, 8]),  ...
        EEG_feature_extractor.extract_relative_power(x, Fs, [8, 13]), ...
        EEG_feature_extractor.extract_relative_power(x, Fs, [13, 20]), ...
        EEG_feature_extractor.extract_relative_power(x, Fs, [20, Fs/2]), ...
        EEG_feature_extractor.extract_abs_median(xg), ...
        EEG_feature_extractor.extract_kurtosis(xg), ...
        EEG_feature_extractor.extract_std(xg), ...
        EEG_feature_extractor.extract_entropy(xg), ...
        EEG_feature_extractor.extract_spectral_mean(x, Fs), ...
        EEG_feature_extractor.extract_fractal_exponent(xg, Fs)   ];

feature_vec = gather(feature_vec);
toc

tic
feature_vec = [
        EEG_feature_extractor.extract_relative_power(x, Fs, [0.5, 4]), ...  
        EEG_feature_extractor.extract_relative_power(x, Fs, [4, 8]),  ...
        EEG_feature_extractor.extract_relative_power(x, Fs, [8, 13]), ...
        EEG_feature_extractor.extract_relative_power(x, Fs, [13, 20]), ...
        EEG_feature_extractor.extract_relative_power(x, Fs, [20, Fs/2]), ...
        EEG_feature_extractor.extract_abs_median(x), ...
        EEG_feature_extractor.extract_kurtosis(x), ...
        EEG_feature_extractor.extract_std(x), ...
        EEG_feature_extractor.extract_entropy(x), ...
        EEG_feature_extractor.extract_spectral_mean(x, Fs), ...
        EEG_feature_extractor.extract_fractal_exponent(x, Fs)   ];
toc